spring.application.name=auth
server.port = 8082
server.port=8083

spring.datasource.url=jdbc:h2:mem:usuariodb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.h2.console.enabled=true

jwt.secret=sabores-globales-clave-secreta-super-segura-2024
jwt.expiration=86400000